apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-simple-build-qaxr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-simple-build-qaxr
    app.kubernetes.io/part-of: build-suite-test-application-jqmi
  name: test-simple-build-qaxr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-simple-build-qaxr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-simple-build-qaxr
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-kfst-tenant/build-suite-test-application-jqmi/test-simple-build-qaxr@sha256:25b64a8c3016f98ea7403569e909932693b1287f8261758b3029bc700921e552
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
